---
title: "RMarkdown & Plotly"
subtitle: "Data Science: Developing Data Product"
author: "Yellow Duck"
date: "September 4, 2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Intructions 

Create a web page using **R Markdown** that features a plot created with **Plotly**.  
Host your webpage on either GitHub Pages, **RPubs**, or NeoCities.  

Your webpage must contain:  

* date that you created the document, and 
* plot created with Plotly  

## Submission: Plotly    

```{r, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
library(datasets)
library(plotly)
Sys.setenv("plotly_username"="yellowduck404")
Sys.setenv("plotly_api_key"="fillHere")

f <- list(
  family = "Courier New, monospace",
  size = 18,
  color = "#7f7f7f"
)
x <- list(
  title = "Weight (1000 lbs)",
  titlefont = f
)
y <- list(
  title = "Miles/(US) gallon",
  titlefont = f
)

p = plot_ly(data = mtcars, x = ~wt, y = ~mpg, 
        color = ~as.factor(cyl), size = ~hp,
        text = ~paste("Weight: ", wt, '<br>MPG:', mpg),
        type = "scatter", mode = "markers") %>%
  layout(
         xaxis = x,
         yaxis = y)
p
```

## Thank You